import LangingPage from "@/components/LangingPage";
import Image from "next/image";
import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>My Textile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dashboard/completelogo.svg" />
      </Head>
      <LangingPage />
    </div>
  );
}
